[package]
name = "proctor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
nix = { version = "0.29", features = ["signal", "process"] }
winnow = "0.7.14"
yansi = "1.0.1"
